name: Crust Pinner Template
on:
  # mannual trigger
  workflow_dispatch:

jobs:
  pin_on_crust:
    name: aDpp 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
